### ISSUE TITLE
Patch breaks visuals completely

### ISSUE THREAD

**Issue by ImAltair1** [EthanRDoesMC/RetroShaderFix#2]
I'm using an RX6700 running on 23.5.2 drivers and i'm playing the v1.09.01 version. Without your patch i can play the game normally however there is no ground textures. When using your patch, the loading of the game is just a black screen and when in game it's basically just a mess. 
Attached is the SHADERERRORDUMP.TXT file.
[SHADERERRORDUMP.TXT](https://github.com/EthanRDoesMC/RetroShaderFix/files/11827351/SHADERERRORDUMP.TXT)

**Comment by EthanRDoesMC** [comment]
Ah, noted. Make sure you’ve got the latest version of the patch? Otherwise I know exactly what’s wrong

**Comment by ImAltair1** [comment]
I downloaded now directly from here and it seems to be working. I assumed NMSLegacyVersionInstaller downloaded the latest version automatically but i was wrong. Sorry for bothering you with such a dumb thing! Keep up the great work
